### ISSUE TITLE
Mouse wheel zoom coordinate is wrong. 2

### ISSUE THREAD

**Issue by MariasStory** [marmelab/EventDrops#100]
I allready reported similar problem #70 
This issue was fixed that time.
Now it is back again. Check the situation in demo.

**Comment by MariasStory** [comment]
Ping 1.

**Comment by MariasStory** [comment]
Ping 2.

**Comment by MariasStory** [comment]
Hi. Long time no see ;-)

I suggest a simple fix for you demo page as well as an implementation workaround.
1) Modify `<div id="eventdrops-demo" style="position: absolute;left: 225px;width: 90%;">`
2) Add at the end of the "demo.js": `document.querySelectorAll(".event-drops-chart")[0].style.cssText = "margin-left: -225px;"`

**Comment by jpetitcolas** [comment]
Sorry for the delay. We rewrote entirely EventDrops to ease maintenance and to fix these weird behaviors. Can you try with the latest version (`1.0.0`)? It should work now, as visible on [the demo](https://marmelab.com/EventDrops/).

For more information about what's new with this version, take a look on our [blog post](https://marmelab.com/blog/2018/01/26/event-drops-1.0-is-out.html).

I am closing the issue. Feel free to re-open it if the issue still occurs.

Thanks for your patience! :)
