### ISSUE TITLE
Usage without npm

### ISSUE THREAD

**Issue by bo2star** [marmelab/EventDrops#101]
How to use this plugin without npm?

**Comment by jpetitcolas** [comment]
It depends. What are you using?

If you don't use any module bundler, you can use unpkg: https://npmcdn.com/event-drops@0.3.0-alpha1

**Comment by bo2star** [comment]
@jpetitcolas I just want to use in static html file.

**Comment by bo2star** [comment]
@jpetitcolas Nevermind. unpkg link works, Thanks.
