### ISSUE TITLE
Left and Right margins not working

### ISSUE THREAD

**Issue by daortizh** [marmelab/EventDrops#107]
Looks like eventDrops function from eventDropGraph.js is not using left, right margins from user configuration data.

Line 42:

`width: dimensions.width,`

Should be similar to line 43:

`height: dimensions.height + finalConfiguration.margin.top + finalConfiguration.margin.bottom,`

**Comment by martinhd** [comment]
in eventdrops.js line 25 ff labelsWidth should be included
    function eventDropGraph(selection) {
        return selection.each(function selector(data) {
            d3.select(this).select('.event-drops-chart').remove();

            const dimensions = {
                width: this.clientWidth-finalConfiguration.labelsWidth,
                height: data.length * finalConfiguration.lineHeight,
            };

            const scales = {
                x: xScale(dimensions.width, [finalConfiguration.start, finalConfiguration.end]),
                y: yScale(data),
            };

            const svg = d3.select(this).append('svg')
                .classed('event-drops-chart', true)
                .attr({
                    width: dimensions.width + finalConfiguration.labelsWidth,
                    height: dimensions.height + finalConfiguration.margin.top + finalConfiguration.margin.bottom,
                });

**Comment by jpetitcolas** [comment]
This should be [solved](https://github.com/marmelab/EventDrops/blob/master/src/index.js#L35) in last `1.0.0` version. But be careful, there are some [BC](https://github.com/marmelab/EventDrops/blob/master/MIGRATION-1.0.md).

Feel free to re-open this issue if you still encounter the issue.
