### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by vanugu** [marmelab/EventDrops#111]
I am having problem installing npm and executing the eventdrops.Can you please help me with the installation and execution.

**Comment by clindo** [comment]
What is the issue, that you are facing? Could you share the error messages?

**Comment by vanugu** [comment]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\karma\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! event-drops@0.3.0-alpha1 prepublish: `make build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the event-drops@0.3.0-alpha1 prepublish script 'make build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the event-drops package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs event-drops
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls event-drops
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\anug0000\e_visual\npm-debug.log

C:\Users\anug0000\e_visual>node app
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\anug0000\e_visual\app'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by osadan** [comment]
I am also having issue installing the package
here is the installation output
> contextify@0.1.15 install /Users/ohad1/Projects/bicks/react/react-basic/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc:131:56: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                       ^
/Users/ohad1/.node-gyp/7.0.0/include/node/v8.h:3292:52: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:182:51: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                  ^
/Users/ohad1/.node-gyp/7.0.0/include/node/v8.h:2949:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:209:38: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                     ^
/Users/ohad1/.node-gyp/7.0.0/include/node/v8.h:2949:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
../src/contextify.cc:210:42: warning: 'GetRealNamedProperty' is deprecated [-Wdeprecated-declarations]
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                         ^
/Users/ohad1/.node-gyp/7.0.0/include/node/v8.h:2949:30: note: 'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
4 warnings and 1 error generated.

 node -v v7.0.0
node-gyp -v v3.4.0
npm  v3.10.8

make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0

**Comment by osadan** [comment]
I removed ~/.node-gyp library and tried to install again  . 
but got the  same errors .
why node-gyp is trying to use contextify.cc at all?

**Comment by clindo** [comment]
I also had similar issue, but it was gone when I opened a **PowerShell** as **Administrator**, and then installing node-gyp

**Comment by osadan** [comment]
I tried sudo(ing) the npm install but got the same issues

**Comment by clindo** [comment]
Which version of Python does you have?

**Comment by osadan** [comment]
Python 2.7.12

**Comment by osadan** [comment]
I tried cloning the project and then build it (not within the npm install) and it worked fine

**Comment by jpdippenaar** [comment]
Hello.  I am on macOS Sierra, Python 7.12, node 7.1 and having the same issue reported by @osadan.  Happy to 'build' the project again, but no idea how.  Please help.

**Comment by erdemci** [comment]
I also get same issue ; 

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! event-drops@0.3.0-alpha1 prepublish: `make build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the event-drops@0.3.0-alpha1 prepublish script 'make build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the event-drops package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs event-drops
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls event-drops
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GitProjects\d3-demos\EventDrops\npm-debug.log


I try many methods (npm install, make build etc.) but not worked for me, Please help. I think this package not stable for npm, please add this package builded / compiled files.

**Comment by jpetitcolas** [comment]
We just removed the `build` after each `npm install`, as it seems to cause some trouble as your stack traces show. Can someone tries again with latest master version and tell us if it works? :)

**Comment by jpetitcolas** [comment]
No more answer. Closing the issue. Feel free to re-open it if it is still the case.
