### ISSUE TITLE
Error: <rect> attribute x: Expected length, "NaN".

### ISSUE THREAD

**Issue by Antonystefano** [marmelab/EventDrops#117]
var startTime = new Date().getTime() - 86400000 * 31;
    var endTime = new Date().getTime();

    var color = d3.scale.category20();
    var timelineContent = document.getElementById('ncs-timeline');
    var parentWidth = timelineContent.offsetWidth;
    var lastHoverId = -1;
    var lastRect = null;

    var eventDropConfig = {
        start: new Date(0),
        end: new Date(),
        minScale: 0,
        maxScale: Infinity,
        width: parentWidth, //1000,
        margin: {
            top: 60,
            left: 150,
            bottom: 20,
            right: 20
        },
        locale: null,
        axisFormat: null,
        tickFormat: [
            [".%L", function(d) { return d.getMilliseconds(); }],
            [":%S", function(d) { return d.getSeconds(); }],
            ["%I:%M", function(d) { return d.getMinutes(); }],
            ["%I %p", function(d) { return d.getHours(); }],
            ["%a %d", function(d) { return d.getDay() && d.getDate() != 1; }],
            ["%b %d", function(d) { return d.getDate() != 1; }],
            ["%B", function(d) { return d.getMonth(); }],
            ["%Y", function() { return true; }]
        ],
        eventHover: function(obj, event) {
        },
        eventHoverLeave: function() {
        },
        eventZoom: null,
        eventClick: function(obj) {
        },
        hasDelimiter: true,
        hasTopAxis: true,
        hasBottomAxis: function(data) {
            return data.length >= 10;
        },
        eventLineColor: 'black',
        eventColor: null
    };

    var eventDropsChart = d3.chart.eventDrops(eventDropConfig)
        .eventLineColor(function(datum, index) {
            return color(index);
        })
        .start(new Date(startTime))
        .end(new Date(endTime));

    var element = d3.select(timelineContent).datum(tdata);
    eventDropsChart(element);

    var divToolTip = d3.select(document.getElementById('ncs-timeline-preview'));

**Comment by antoniohof** [comment]
The version on the README file is not updated. This bug has been fixed on this version:
https://gist.githubusercontent.com/thoka/ca508531e9a016fb815477621f9d6aae/raw/32b3a1e79208a840666882fec60804c68a96bf7f/eventdrops.js

download the file and and put directly on your project.

**Comment by jpetitcolas** [comment]
Closing as no more feedbacks.
