### ISSUE TITLE
installing event-drops  windows 10--angular-cli  get failure -error C2039 

### ISSUE THREAD

**Issue by azulay7** [marmelab/EventDrops#121]
..\src\contextify.cc(150): error C2039: 'SetAccessCheckCallbacks': is not a member of 'v8::ObjectTemplate' [C:\Users\myName\WebstormProjects\d3Practice\node_modules\contextify\build\contextify.vcxproj]

runing on th machine:
python 2.7
node 7.5.0
npm 4.12
windows-build-tools
vs2015 community

help will be highly appriciated :)

**Comment by jpetitcolas** [comment]
May it be related to #111? 

Can you try using the current master branch, pointing on `marmelab/EventDrops` in your package.json instead of a given tag version?

**Comment by azulay7** [comment]
Yes it is related. thank you! now the library does compile.
but when I run 'npm run'  I cannot see the chart:
![image](https://cloud.githubusercontent.com/assets/19120/24331274/62815a74-1239-11e7-865c-e8ce5a4f4059.png)

**Comment by jpetitcolas** [comment]
@azulay7: any JS error in the console?

**Comment by azulay7** [comment]
well, it's just got fixed by itself in the latest version.
