### ISSUE TITLE
npm upgrade

### ISSUE THREAD

**Issue by osadan** [marmelab/EventDrops#127]
when I am trying to download from npm I still receive the old version (actually) I still receive the contexitfy node-gyp error .

**Comment by jpetitcolas** [comment]
I updated the issues we should address before releasing the 0.3 version. You can retrieve the list [here](https://github.com/marmelab/EventDrops/milestone/4). 

Meanwhile, you can still use last master version of EventDrops using something like, in your `package.json` file:

``` js
"event-drops": "marmelab/EventDrops"
```

You can eventually specify a given commit hash, suffixing the previous statement by `#[HASH]`.

**Comment by osadan** [comment]
o.k 
I will give it a try.
another problem I am facing is that I want to import eventdrops in webpack as common and not as umd (using import for the lib/eventDrops.js)

**Comment by jpetitcolas** [comment]
We released `1.0.1` version recently. 

For other issues, can you open some dedicated issues? :)
