### ISSUE TITLE
How to get the time range/extent of the current view on zoomend?

### ISSUE THREAD

**Issue by sfairgrieve** [marmelab/EventDrops#128]
First, let me say that EventDrops is awesome!  

I'm not super familiar with D3 zooming behavior, so forgive me if this is easy.  I'm trying to write some code in the `zoomend` event handler that gets the time range/extent of the current view of the EventDrops chart after the user has zoomed in order to use this info. to filter the data that's displayed in other views outside of the EventDrops chart.  I see that I can use `d3.event.target` to get some information, but it's not obvious how to translate that information into a date range.  I'm assuming there's a scaling function that's used by EventDrops to translate x coordinates into date values, but I'm not sure of the easiest way to access that in order to produce date values.  Any help you can provide would be greatly appreciated!

**Comment by bmasch** [comment]
The documentation suggests that a zoomend relays the d3.scale (from which one could get the limits) to the specified function, but it is actually relaying the datum (and that includes all data). 

However, I discovered that you can scrape the extent from the extremum values displayed (usually) above the chart. 
...
.zoomend(zoomEnd)

var zoomEnd = function(){
	var format1 = d3.time.format("%d %B %Y");
	var min = d3.select(".minimum").text();
	var max = d3.select(".maximum").text();
	console.log(format1.parse(min));
	console.log(format1.parse(max));
}

You could then filter the data to be within those bounds.

**Comment by sfairgrieve** [comment]
@bmasch thanks for the help!  I'll give this a try.

**Comment by jpetitcolas** [comment]
For information, I just opened a PR (still work to do on it yet) which may solve your needs: https://github.com/marmelab/EventDrops/pull/151

**Comment by jpetitcolas** [comment]
In last version (`1.x`), you can retrieve current displayed time range using `chart.scale()`, as shown on [the demo](https://github.com/marmelab/EventDrops/blob/master/demo/demo.js#L19-L20).

Be careful: `1.0` version brought several [breaking changes](https://github.com/marmelab/EventDrops/blob/master/MIGRATION-1.0.md). To get an overview of what's new in this new version, take a look on [our blog post](https://marmelab.com/EventDrops/).
