### ISSUE TITLE
Filter and clipPath will not work as expected in svg

### ISSUE THREAD

**Issue by Rekhajikki** [marmelab/EventDrops#135]
Hi ,

I'm using the event drops plugin in ember app.Seems like the filter and clipPath will not work as expected in svg in ember app.Kindly help me out to fix the issue.
I tried to fix following the below link
 http://stackoverflow.com/questions/26135065/broken-svg-filter-id-link-when-using-history-api-with-ember-cli/31303293#31303293 

but it did not work out for me.

Thanks,
Rekha Jikki

**Comment by jpetitcolas** [comment]
In last version (`1.0`), we don't use `clip-path` anymore. But be careful, there are some [breaking changes](https://github.com/marmelab/EventDrops/blob/master/MIGRATION-1.0.md). 

Feel free to re-open this issue if you still encounter it.
