### ISSUE TITLE
minimum and maximum dates won't update on zooming

### ISSUE THREAD

**Issue by azulay7** [marmelab/EventDrops#136]
I just git clone the project (0.3.0-alpha) and run the demo.
the bug occurs there.

**Comment by azulay7** [comment]
anybody??? 😕

**Comment by jpetitcolas** [comment]
Can you try with a latest version? 

Sorry for the delay. :)

**Comment by azulay7** [comment]
latest version v0.3.0alpha2 not running at all.
npm start gives an error:

'No configuration file found and no entry configured via CLI option.
When using the CLI you need to provide at least two arguments: entry and output.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.'

**Comment by carey-at-trustnetworks** [comment]
I'm having the same problem with release 0.3.1-alpha4 as well as the HEAD of the repo. The dates above the top x-axis don't change on zoom, and the right hand one is not aligned right. I have tried to fix this myself and wasted a good deal of the day doing that. I want to use EventDrops to demo what is possible as far as zooming time-based data, and it's not going well 😄 .

Thanks in advance for your help. I am attaching two screen shots.

![after-zoom](https://user-images.githubusercontent.com/29540585/32234653-5047a156-be55-11e7-8467-7c34fbf71f65.png)
![before-zoom](https://user-images.githubusercontent.com/29540585/32234654-506a201e-be55-11e7-822d-b14d2a5a06c6.png)

**Comment by kenyoneda** [comment]
Any updates on this? Dates on top of the demo still do not work. Trying to look through the source code but new to javascript.

**Comment by jpetitcolas** [comment]
Hi there!

We are very close of a 4.0 version (release next week). It also fixes this issue. If you want to give it a try now, you can use the `rewrite` branch.
