### ISSUE TITLE
Run standalone in an nginx environment

### ISSUE THREAD

**Issue by pkanthi** [marmelab/EventDrops#139]
Can this package be used without NodeJS? I have a nginx based system and want to use this widget as an add on to existing JS based widgets from d3 gallery. Any help on how to do that would be appreciated.

**Comment by jpetitcolas** [comment]
The built files are generated only when deploying to `npm`. Yet, if you don't use `npm`, you can [still use unpkg](https://github.com/marmelab/EventDrops/issues/101). It would give you access to the JS available in released bundle.
