### ISSUE TITLE
d3.chart.eventDrops( ) undefined 

### ISSUE THREAD

**Issue by JulianoEngineer** [marmelab/EventDrops#141]
I'm using the latest version of `EventDrops`, with the latest version of `D3` . In my code I have the following line:
`
 var eventDropsChart = d3.chart.eventDrops();`

As described on readme.md, but the execution of the code returns:

```
Uncaught TypeError: Cannot read property 'eventDrops' of undefined
    at FileReader.reader.onloadend
```
Exist one specific version of D3 to be used? Chart in D3 Module is no longer supported?

**Comment by jpetitcolas** [comment]
Indeed, I reproduced the issue on following JSFiddle: https://jsfiddle.net/rdj23ybj/

Looking at it.

**Comment by jpetitcolas** [comment]
It was indeed an issue with current EventDrops version. I opened a PR to fix it. Once merged, we'll release another beta version. 

Thanks for reporting! :)

**Comment by JulianoEngineer** [comment]
This new version worked for me @jpetitcolas . But now I have a new error described in #146 .

Thank you

**Comment by carpiediem** [comment]
I'm getting the same error, now that unpkg.com has been updated.  What was the previous version that was working a couple weeks ago?  https://unpkg.com/event-drops@0.3.1-alpha3/dist/eventDrops.js maybe?

**Comment by mozhdehhmd** [comment]
I have the same error  "_Uncaught TypeError: Cannot read property 'eventDrops_' of undefined", and my code is :
`    <!DOCTYPE html>

    <html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta charset="utf-8" />
    <title></title>
    <link href="https://unpkg.com/event-drops/dist/style.css" rel="stylesheet" />
    </head>
    <body>
    <div id="chart_placeholder"></div>
    <script src="https://unpkg.com/d3"></script>
    <script src="https://unpkg.com/event-drops@1.0.1/dist/index.js"></script>
    <script type="text/javascript">
        var data = [{ name: "http requests", data: [new Date('2017/09/15 13:24:54'), new Date('2017/09/15 
    13:25:03'), new Date('2017/09/15 13:25:05')] },
      { name: "SQL queries", data: [new Date('2017/09/15 13:24:57'), new Date('2017/09/15 13:25:04'), new 
    Date('2017/09/15 13:25:04')] },
      { name: "cache invalidations", data: [new Date('2017/09/15 13:25:12')] }];

        var eventDropsChart = d3.chart.eventDrops();

        d3.select('#chart_placeholder')
            .datum(data)
            .call(eventDropsChart);


    </script>
    </body>
    </html>`

**Comment by mbirabhadra** [comment]
what happened to the solution??

**Comment by carpiediem** [comment]
@mbirabhadra , you'll need to point to an older version or [migrate your code](https://github.com/marmelab/EventDrops/blob/master/MIGRATION-1.0.md) for v1.0.1.
