### ISSUE TITLE
Allow customization of the vertical axis labels

### ISSUE THREAD

**Issue by kwesterfeld** [marmelab/EventDrops#142]
I want to remove the (NNN) appended to the labels (text) from lib/drawer/labels; allow configuration to override this or to provide a drawing function.

**Comment by jpetitcolas** [comment]
It is already doable from the `1.0.0` version (currently `1.1.1`), using the `label.text` configuration parameter, as shown on this [JSFiddle](https://jsfiddle.net/6a9m4wrg/):

```js
var chart = eventDrops({
    label: {
      text: d => d.name,
    }
});
```
