### ISSUE TITLE
npm install fails on gyp-build of contextify

### ISSUE THREAD

**Issue by rtm** [marmelab/EventDrops#148]
Upon doing 

    npm install --save event-drops

I get the error

```
2757 error argv "/home/rtm/.nvm/versions/node/v7.2.1/bin/node" "/home/rtm/.nvm/versions/node/v7.2.1/bin/npm" "install" "--save" "event-drops"
2758 error node v7.2.1
2759 error npm  v3.10.10
2760 error code ELIFECYCLE
2761 error contextify@0.1.15 install: `node-gyp rebuild`
```

A bit of research reveals that `contextify` is obsolete. `contextify@0.1.15` is being brought in by `json@1.0.0` which is being brought in by `d3@.3.5.3` which is being brought in by `event-drops`. Evidently there is a newer version of `jsdom` without the `contextify` dependency:

```
$ npm install --save event-drops --dry-run
nemmadi-console@1.5.0-alpha2 /home/rtm/repos/nims/console
+-- event-drops@0.3.0-alpha1
| `-- d3@3.5.3
|   `-- jsdom@1.0.0
|     +-- contextify@0.1.15
|     | `-- bindings@1.2.1
|     +-- htmlparser2@3.9.2
|     | `-- domhandler@2.4.1
|     `-- parse5@1.5.1
```

I'm confused by this because `package.json` in the `event-drops` repo lists the d3 dependency as `d3@^4.7.0`.

**Comment by fzaninotto** [comment]
Same here.

**Comment by jpetitcolas** [comment]
@rtm: which version are you using? In last version, we indeed need the D3 4 version.

@fzaninotto, if you still have the use case, I would like to test it on your machine.

**Comment by jpetitcolas** [comment]
Closing as no more feedbacks. Feel free to re-open the issue if you still encounter it. :)
