### ISSUE TITLE
index.js is not in published output on npm

### ISSUE THREAD

**Issue by blugavere** [marmelab/EventDrops#159]

**Comment by djhi** [comment]
Should be fixed in last alpha. However, we're struggling with webpack currently: event-drops is including d3 and it shouldn't.

**Comment by djhi** [comment]
Fixed by #161 
Published under `0.3.1-alpha4`

**Comment by blugavere** [comment]
would dependency injection be an option? -> `function eventDrops(d3, config = {}) {`

**Comment by djhi** [comment]
Are you asking because you import d3 through webpack ?

**Comment by blugavere** [comment]
ya did webpack externals solve the problem?

**Comment by djhi** [comment]
You can use the `ProvidePlugin`:
```js
new webpack.ProvidePlugin({
    d3: 'd3',
})
```

And in your code, import `d3` like this:
```js
import * as d3 from 'd3';
```

That's how we solved this currently.
