### ISSUE TITLE
can't run npm start

### ISSUE THREAD

**Issue by azulay7** [marmelab/EventDrops#164]
C:\{my_home}\Documents\EventDrops>webpack-dev-server --colors --devtool cheap-module-inline-source-map --host=0.0.0.0

No configuration file found and no entry configured via CLI option.
When using the CLI you need to provide at least two arguments: entry and output.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.

I run npm build first. I just want to check the demo with current features.
am I missing something?

**Comment by jpetitcolas** [comment]
According to the Makefile, you should instead run:

```
./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.demo.js --hot --inline --colors --host=0.0.0.0
```

There is no `webpack.config.js` default file. Instead you should specify either the demo one, or the lib build one.

All useful commands should be listed in the `Makefile`. :)

**Comment by AydinChavez** [comment]
First:
npm run build

Then the command from jpetitcolas above or shorter:
`webpack-dev-server --config webpack.demo.js --hot --inline --colors --host=0.0.0.0`

Also I had to replace 
`import eventDrops from '../dist';` 
with
`import eventDrops from '../dist/eventDrops';`
in the file `demo/demo.js`
to make it work.
