### ISSUE TITLE
Where's eventDrops.js? 

### ISSUE THREAD

**Issue by jasonnorm** [marmelab/EventDrops#172]
Probably not an issue but rather my own ignorance, but why is there no eventDrops.js file in the src directory?

The only one I could find was in the test/karma directory but trying to use that file I get an error related to the import statement. 

What am I doing wrong?

I just want to have the library called by the client as you explain in the README:

```
Usage

Include the `src/eventDrops.js` script in your page after d3:

<script src="path/to/d3.js"></script>
<script src="src/eventDrops.js"></script>

In the HTML source, create a new EventDrops chart, bind data to a DOM element, then call the chart on the element.

var eventDropsChart = d3.chart.eventDrops();
d3.select('#chart_placeholder')
  .datum(data)
  .call(eventDropsChart);`

```

**Comment by jpetitcolas** [comment]
Indeed, README seems outdated. We do not commit transpiled files anymore. However, if you need to include the `eventDrops.js` file without using any module bundler (such as Webpack), I suggest you use unpkg: https://unpkg.com/event-drops@0.3.1-alpha4/dist/eventDrops.js

Please let me know if you need extra information. I'll make a PR to update the README. :)
