### ISSUE TITLE
The documentation page uses [name: ... , data:...] as example, shouldn't it be dates?

### ISSUE THREAD

**Issue by Wulala526** [marmelab/EventDrops#177]
I tried:

``` js
var data = [
  { name: "http requests", data: [new Date('2014/09/15 13:24:54'), new Date('2014/09/15 13:25:03'), new Date('2014/09/15 13:25:05'), ...] },
  { name: "SQL queries", data: [new Date('2014/09/15 13:24:57'), new Date('2014/09/15 13:25:04'), new Date('2014/09/15 13:25:04'), ...] },
  { name: "cache invalidations", data: [new Date('2014/09/15 13:25:12'), ...] }
];
```

as documented but there is no points drawn after initialization.
After I changed "data:" to "dates:" it worked.
Is that a typo? Thanks.

**Comment by jpetitcolas** [comment]
It sounds strange as it should be [data](https://github.com/marmelab/EventDrops/blob/master/src/drop.js#L4), at least in `1.x` versions. Can you give us more context?

**Comment by asiby** [comment]
@Wulala526, I think that you forgot something. Your `data` key has the wrong array.

The following was copied from the documentation ...

```javascript
const repositoriesData = [
    {
        name: 'admin-on-rest',
        data: [{ date: new Date('2014/09/15 14:21:31') } /* ... */],
    },
    {
        name: 'event-drops',
        data: [{ date: new Date('2014/09/15 13:24:57') } /* ... */],
    },
    {
        name: 'sedy',
        data: [{ date: new Date('2014/09/15 13:25:12') } /* ... */],
    },
];
```

You can see that the array passed to the `data` property is an array of JSON objects ... unlike your array of dates.

And each JSON in the array must have a `date` property that contains the actual date.

I think that this issue can be close.

**Comment by jpetitcolas** [comment]
Yes, I'm closing the issue. Thanks @asiby. 

Moreover, we updated some error messages. Now, instead of having an enigmatic message, you should get something like: 

> No drops data has been found. It looks by default in the `data` property. You can use the `drops` configuration parameter to tune it.
