### ISSUE TITLE
Zoom breaks, if data has no .date attribute.

### ISSUE THREAD

**Issue by thoka** [marmelab/EventDrops#184]
While running eventdrops with data like

```json
{ "name" : [{ "date_sent": "2017-08-11" }] }
```
and 

```javascript
.date( d => new Date(d.date_sent) )
```
the graph is shown nicely.

After a zoom event, all cx values are set to 0 while exceptions like
```
Error: <circle> attribute cx: Expected length, "NaN".
```
show up in the console.

**Comment by andygock** [comment]
I may be having a similar issue, with cx attribute problem:

    Unexpected value NaN parsing cx attribute.

But I'm using (from example):

        var data =  [
            { name: "http requests", data: [new Date('2014/09/15 13:24:54'), new Date('2014/09/15 13:25:03'), new Date('2014/09/15 13:25:05')] },
            { name: "SQL queries", data: [new Date('2014/09/15 13:24:57'), new Date('2014/09/15 13:25:04'), new Date('2014/09/15 13:25:04')] },
            { name: "cache invalidations", data: [new Date('2014/09/15 13:25:12')] }
        ];

Graph renders, when zoom or scrolling, the JS error is shown x7 (once for each element).

**Comment by thoka** [comment]
This is how the zoom function looks like in the compiled code:
```js
            e.default = function(e, r, n, a, i) {
                var s = function(r) {
                        var s = d3.event.transform.rescaleX(n.x);
                        (0, u.boolOrReturnValue)(a.hasTopAxis, r) && e.selectAll(".x-axis.top").call(d3.axisTop().scale(s)), (0, u.boolOrReturnValue)(a.hasBottomAxis, r) && e.selectAll(".x-axis.bottom").call(d3.axisBottom().scale(s));
                        var c = (0, o.default)((0, l.default)(e.select(".labels"), {
                            x: s
                        }, a), 100);
                        t.requestAnimationFrame(function() {
                            e.selectAll(".drop-line").selectAll(".drop").attr("cx", function(t) {
                                return s(new Date(t.date))
                            }), c(r), i && i(r)
                        })
                    },
                    c = d3.zoom().scaleExtent([a.minScale, a.maxScale]).on("zoom", s).on("end", a.zoomend);
                return e.call(c), c
            }
```

I would expect it to be simmilar to the compiled draw function
```js
     function(t, e, r) {
        "use strict";
        Object.defineProperty(e, "__esModule", {
            value: !0
        }), e.default = function(t, e, r) {
            return function(n) {
                var a = t.selectAll(".drop-line").data(n).enter().append("g").classed("drop-line", !0).attr("width", e.x.range()[1]).attr("transform", function(t, r) {
                        return "translate(0, " + e.y(r) + ")"
                    }).attr("fill", r.eventLineColor),
                    o = a.selectAll(".drop");
                o.data(function(t) {
                    return t.data
                }).enter().append("circle").classed("drop", !0).attr("r", 5).attr("cx", function(t) {
                    return e.x(r.date(t))
                }).attr("cy", r.lineHeight / 2).attr("fill", r.eventColor).on("click", r.click).on("mouseover", r.mouseover).on("mouseout", r.mouseout), o.exit().on("click", null).on("mouseout", null).on("mouseover", null).remove(), a.exit().remove()
            }
        }
```

but it seems not to use config.date at all.

**Comment by thoka** [comment]
I do not understand the compile machinery yet, but maybe changing
```js
export const onRequestAnimationFrameFactory = (...)
```
to 
```js
export onRequestAnimationFrameFactory = (...)
```
in `zoom.js` would fix this.

**Comment by thoka** [comment]
After building the distribution myself my error vanished.
Without further thinking I followed the current readme and used the source from `https://unpkg.com/event-drops` for my experiments, which resolves to `/event-drops@0.3.1-alpha4`.

**Comment by andygock** [comment]
@thoka  Are you saying that following the README doesn't work, and that `https://unpkg.com/event-drops` isn't up to date?

I'm using:

```
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://unpkg.com/event-drops"></script>
```

And getting the same problem you initially described.

**Comment by thoka** [comment]
It seems so. 

unpkg is at 0.3.1-alpha4, the last tagged version from 2017-06-19 11:45:24.
The code in the repo is some commits newer. 

Quoting unpkg:

> You may also use a semver range or a tag instead of a fixed version number, or omit the version/tag entirely to use the latest tag.

**Comment by thoka** [comment]
I've put the current build at
```
<script src="https://gist.github.com/thoka/ca508531e9a016fb815477621f9d6aae.js"></script>
```
or not uglified at
```
<script src="https://gist.github.com/thoka/f66e1b154b851fb8dd4e2ab30b19b5b8.js"></script>
```

**Comment by antoniohof** [comment]
I have the same problem. Where can I get the full compiled code without error? Your links are not working.
Thanks

**Comment by antoniohof** [comment]
Ok, I copied the files and saved them and now its working. You should update the README with the newest build
