### ISSUE TITLE
with older version of d3

### ISSUE THREAD

**Issue by gkamle** [marmelab/EventDrops#199]
Hi,

Iam using older version of d3 (3.5.17). I want this chart to work with this d3 version.
can you please guide me what to do?

Thanks & Regards,
Govardhan

**Comment by codeInCat** [comment]
me too

**Comment by jpetitcolas** [comment]
We just released [1.0 version](https://marmelab.com/blog/2018/01/26/event-drops-1.0-is-out.html), and it requires D3.js version 4 at least. We don't plan to support older version anymore.
