### ISSUE TITLE
Add data to event

### ISSUE THREAD

**Issue by miguelgazela** [marmelab/EventDrops#20]
Is it possible to add data to each event? If not, are you planning a similar feature?

I'm doing a chat analyzer and I would like to add the content of the message to the event to display it on hover.

Regards

**Comment by ThieryMichel** [comment]
As long as you can map your additional data to the event (the date) you can display any info you want on eventHover. since you have access to the date here, via the element.
simply use: 
```
d3.select(el).data()[0];
```
to get the date of the event.

**Comment by miguelgazela** [comment]
But there's no way of knowing in which eventLine the event is located right?

**Comment by ThieryMichel** [comment]
To get the name of the event lines do:
```
d3.select(el.parentNode).data()[0].name
```
The parent element of the event element, being the line, d3 can acces the data binded to it. This include its name.
