### ISSUE TITLE
sample created but not succeeded

### ISSUE THREAD

**Issue by gkamle** [marmelab/EventDrops#200]
Hi 
Iam using d3 version 4.12.2
and eventDrops.js downloaded from this below link

https://gist.githubusercontent.com/thoka/ca508531e9a016fb815477621f9d6aae/raw/32b3a1e79208a840666882fec60804c68a96bf7f/eventdrops.js

and my code is

``` xml
<html>
    <head><title>asdasd</title>
        <script src="./d3.js"></script>
        <script src="./eventDrops.js"></script>
        <script lang="javascript">
            function test() {
                var hardData = [{
    name: 'sensor1',
    dates: [
        new Date(1458068401000),
        new Date(1458068401000),
        new Date(1458068403000),
        new Date(1458068404000),
        new Date(1458068405000),
        new Date(1458068406000),
        new Date(1458068411000),
        new Date(1458068413000),
        new Date(1458068415000),
        new Date(1458068416000),
    ],
}];

var eventDropsChart = d3.chart.eventDrops();

d3.select('body')
    .datum(hardData)
    .call(eventDropsChart);
            }
        </script>
    </head>
    <body onload="test()"></body>
</html>

```

Thanks & Regards,
Govardhan

**Comment by jpetitcolas** [comment]
I'm not sure what is the version in the link you provided. I advise you to use the official release on https://unpkg.com/event-drops. Caution: the [API changed](https://github.com/marmelab/EventDrops/blob/master/MIGRATION-1.0.md) compared to previous versions. 

If you need some support, feel free to ask another questions on StackOverflow. :)
