### ISSUE TITLE
Fix demo deployment

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/EventDrops#205]
Demo deployment doesn't work anymore, probably because we delete the `gh-pages` branch at each deployment.

**Comment by aardvark82** [comment]
Hi - I've also noticed that the links in the instructions when not using a module bundler are broken:
is this the same issue? or should I create a new one. 

https://unpkg.com/event-drops@1.0.0/dist/eventDrops.css
and
https://unpkg.com/event-drops/dist/eventDrops.js

From https://github.com/marmelab/EventDrops:

"If you don't use any module bundler such as Webpack, we recommend using EventDrop script available on unpkg.com. Grabbing last versions of the library is as simple as:

<link href="https://unpkg.com/event-drops/dist/eventDrops.css" rel="stylesheet" />
<script src="https://unpkg.com/d3"></script>
<script src="https://unpkg.com/event-drops/dist/eventDrops.js"></script>
"

**Comment by jpetitcolas** [comment]
Good catch @aardvark82! Indeed, documentation seems wrong. Instead, you should use: 

```
https://unpkg.com/event-drops@1.0.0/dist/index.js
```

As link. In case of doubt, you can check directly in the `dist` folder: https://unpkg.com/event-drops/dist/
