### ISSUE TITLE
Can i use d3.js(3.5.10)?

### ISSUE THREAD

**Issue by codeInCat** [marmelab/EventDrops#207]
I want to use EventDrops in my project,but the js file has already require d3.js(3.5.10),how can i use it with d3.js(3.5.10)? sorry,my english is poor.

**Comment by jpetitcolas** [comment]
We just released [1.0 version](https://marmelab.com/blog/2018/01/26/event-drops-1.0-is-out.html), and it requires D3.js version 4 at least. We don't plan to support older version anymore.
