### ISSUE TITLE
Create a bower package

### ISSUE THREAD

**Issue by lucasponce** [marmelab/EventDrops#21]
Hello,
I see that there is a npmjs package what is very nice.
It can be also helpful if we can use bower repository.
Is it possible to create a new package in that repository ?
Thanks

**Comment by ThieryMichel** [comment]
I will look into it.

**Comment by vrockai** [comment]
Kudos for making this happen! Can you please set the dependencies in the bower.json, too? Like the d3 and whatever else is needed. It's important for plugins like wiredep to work correctly. Thanks.

**Comment by jsCTim** [comment]
Hello,

Are you going to release a new version for bower support?  it looks like its out of date.

Thanks!

**Comment by jpetitcolas** [comment]
The real question here is: should we continue to support Bower?

I propose to remove the `bower.json` file from this package, in profit of `npm` use only. Indeed, using `npm` is more appropriate for package managers such as Webpack or Browserify, which work like a charm for front-end.

Here is a more detailed post: [Why we should stop using Bower, and how to do it?](https://gofore.com/ohjelmistokehitys/stop-using-bower/)

If you still want to use Bower, you can however use the GitHub URL like:

``` js
{
    "dependencies": {
        "eventDrops": "marmelab/EventDrops#0.1.2"
    }
}
```
We are going to tag each new release both on `npm` and GitHub.

What do you think about the Bower deprecation?

**Comment by jpetitcolas** [comment]
And, to answer to former question, we'll try to release the 0.2.0 probably during next week, once all current issues would be fixed. Not a 0.1.x, as the core has been fully rewritten for better code splitting.

**Comment by jsCTim** [comment]
We do use bower a lot, not webpack, etc. our tooling is built around what we have with gulp, bower, etc. when we were first building up our environment. 
  
I don't have a concern with dropping bower support, since like you said, I can refer to a release directly.  Its more important to have the release  :smiley:  Looking forward to seeing it!
