### ISSUE TITLE
configuration in event drop to set chart a line chart type rather than a bubble chart

### ISSUE THREAD

**Issue by meenakshi1969** [marmelab/EventDrops#213]
Hi Sir,
I want to ask is there any configuration in event drop to set chart a line chart rather than a bubble .And where is API documentation for it?

**Comment by jpetitcolas** [comment]
Hi,

This is currently not supported, but is a popular demand. It will probably implemented in the future. Feel free to send a PR if you get some time available to work on it. :)

See: https://github.com/marmelab/EventDrops/issues/138

**Comment by meenakshi1969** [comment]
ok thanks.
