### ISSUE TITLE
Broken chart after version change unpkg

### ISSUE THREAD

**Issue by ElenaNicoleta** [marmelab/EventDrops#219]
Hi,

I was using previous version of eventDrops from unpkg (event-drops@0.3.1-alpha4). After latest release I got the following error message:

```
filterData.js:3 Uncaught TypeError: t.filter is not a function
    at n (filterData.js:3)
    at SVGTextElement.i (labels.js:8)
    at SVGTextElement.<anonymous> (d3.v4.min.js:2)
    at ut.each (d3.v4.min.js:2)
    at ut.text (d3.v4.min.js:2)
    at labels.js:24
    at index.js:85
    at HTMLDivElement.<anonymous> (index.js:58)
    at ut.each (d3.v4.min.js:2)
    at e (index.js:37)
```

How can I fix this? Can i still use event-drops@0.3.1-alpha4?

**Comment by jpetitcolas** [comment]
We are using semver on this repository, hence the `1.0.0` brings several breaking changes. On this case, we renamed `filteredData` to `visibleDataInRow`. I guess this is where your issue comes from. :)

For migration details, please refer to the [MIGRATION-1.0.md file](https://github.com/marmelab/EventDrops/blob/master/MIGRATION-1.0.md). If you want to get an overview of all improvements of this new version, we published a [summary blog post](https://marmelab.com/blog/2018/01/26/event-drops-1.0-is-out.html).

**Comment by ElenaNicoleta** [comment]
Hi, 
Thank you! This issue seems to be solved now. But i have one more question for you.
Some times my chart looks very strange, as in attached picture. After i clear my browser's cache, it shows up normal again. How can I change this behavior?
 
![activity_chart](https://user-images.githubusercontent.com/36312184/36253922-d3274bee-1251-11e8-899f-14c5a54f7dac.jpg)

**Comment by jpetitcolas** [comment]
Can you check your console for errors? Without any log, it would be difficult to guess. :)

**Comment by ElenaNicoleta** [comment]
"Error: <rect> attribute width: A negative value is not valid. ("-160")" this is the only one i have in console

**Comment by jpetitcolas** [comment]
Can you ensure the root div has correct width? Moreover, in order to ease debugging, can you reproduce your use case in this [JSFiddle](https://jsfiddle.net/6rqxusw5/9/)?

**Comment by hlaingwintunn** [comment]
Hello,
My chart not show correctly in angular project. Can you help me??
Console error is   'svg attribute width: A negative value is not valid. ("-20")'
![webp net-resizeimage](https://user-images.githubusercontent.com/26534753/40291995-17ddcc6a-5cfb-11e8-935f-2078114969e3.jpg)

**Comment by nicoleta2540** [comment]
Any update on this? Still having same issue

**Comment by jpetitcolas** [comment]
@nicoleta2540: it would be far faster to solve if we have access to a [JSFiddle](https://jsfiddle.net/6rqxusw5/9/) reproducing the issue. :)

**Comment by hlaingwintunn** [comment]
Hello,
I already fixed my problem. That is not a chart problem. last time I used Eventdrop chart inside hidden Tag. This hidden tag make the chart width wrong. Thank you.

**Comment by ElenaNicoleta** [comment]
Hello,
This issue can be closed. hlaingwintunn was right,  it was not a chart problem.
Thank you!
