### ISSUE TITLE
axis in negative values

### ISSUE THREAD

**Issue by gkamle** [marmelab/EventDrops#221]
Hi,
I have created a sample. The application is working but the axis goes in negative values.
Iam sending a plunker sample. Please help me.

http://plnkr.co/edit/e5UvCSAxLg93WSMURZG3?p=preview

Thanks & Regards,
Govardhan

**Comment by jpetitcolas** [comment]
It seems you committed an error in your jQuery selector line 9:

```diff
- var result = $("<div>").css({
+ var result = $("div").css({
```

This way, drops are drawn correctly. Moreover, the stylesheet is missing to get separator lines. Don't forget to add the `https://unpkg.com/event-drops/dist/style.css` style.
