### ISSUE TITLE
Error: Invalid value for <circle> attribute cx="NaN"

### ISSUE THREAD

**Issue by jeraymond** [marmelab/EventDrops#225]
Hello,

I'm trying to use EventDrops 1.0.1 [without a Module Bundler](https://github.com/marmelab/EventDrops/tree/v1.0.1#without-a-module-bundler). When the chart renders all the drops are stuck on the left side of the graph. The the console logs I see JavaScript error 

```
Error: Invalid value for <circle> attribute cx="NaN"
```

It seems like there is something wrong calculating the x-axis value. Here is a [repro of the issue](https://jsfiddle.net/p661ecLg/11/). Any ideas?

**Comment by jpetitcolas** [comment]
It seems you have forgotten to specify the `date` function. Here is the [fixed version](https://jsfiddle.net/p661ecLg/14/).

```diff
var chart = eventDrops({
	range: {
	  start: new Date('03/01/2018 6:55:11 PM'),
    end: new Date('03/05/2018 6:55:11 PM')
  },
  drop: {
+    date: d => d.date,
  }
});
```

**Comment by jeraymond** [comment]
Thanks that fixed the issue.
