### ISSUE TITLE
explicitly named "date" property in filteredData?

### ISSUE THREAD

**Issue by gassc** [marmelab/EventDrops#227]
I'm really liking this tool and the way it abstracts away some of the boilerplate required to get a D3 visualization like this up and running. So, thank you. 

<hr>

I think I'm noticing an issue that may be related to this line where `filteredData` is established (but I'm not entirely sure):
https://github.com/marmelab/EventDrops/blob/62328de3bed3888eb1a0be849d98b5afc5db191f/src/index.js#L88

Does this mean that the event data objects must always have a `date` property, with that name exactly?  

What I'm seeing: 

If my event objects don't explicitly have a `date` property (in my case my data has a `datetime` property instead), the resulting `filteredData` object's `data` property is empty while the `fullData` property is complete (so nothing appears on the timeline).

![image](https://user-images.githubusercontent.com/10030148/37045739-a36525ce-2134-11e8-94a8-25250ecb9d29.png)

If I run a data transformation ahead of time, renaming my `datetime` property to `date`, then things work as expected. 

Running a transformation ahead of time is not an issue at all (and in fact I need to do that anyway, just like in the [demo](https://github.com/marmelab/EventDrops/blob/62328de3bed3888eb1a0be849d98b5afc5db191f/demo/demo.js#L79)), but I just wanted to confirm what I'm seeing.

**Comment by jpetitcolas** [comment]
Good catch! We indeed should use the `config.drop.date` function here. It definitively worths a PR! :)

**Comment by jpetitcolas** [comment]
Released in 1.0.2.
