### ISSUE TITLE
Reverse chart (most recent date -> to oldest date)

### ISSUE THREAD

**Issue by jeraymond** [marmelab/EventDrops#229]
In the EventDrops 0.3 I was able to create a chart that displayed the events with most recent events on the left of the chart and the oldest on the right. I did this by reversing the data series and start/end ranges.

In EventDrops 1.x this doesn't work the same way. It acts as if the the event data is always sorted and displayed oldest on the left and newest on the right. Inverting the start/end range seems to be invalid and displays no events when inverted.

Is there a way to draw the chart in the opposite direction with newest events on the left in EventDrops 1.x?

**Comment by jpetitcolas** [comment]
We did it involuntarily. Yet, I just opened a [pull request](https://github.com/marmelab/EventDrops/pull/231) to address it. It should be fixed on 1.0.3 then.

And don't worry about the future: we added a test to prove this feature should be kept. :)

**Comment by jeraymond** [comment]
Great, thanks a lot for the fix.

**Comment by jpetitcolas** [comment]
It has just been published in `1.1.0` version (and not `1.0.3` as stated above, as this is a new feature).
