### ISSUE TITLE
(node:5507) UnhandledPromiseRejectionWarning: TypeError: unspentOutputs.map is not a function     at Object.makeTransferTransaction (/home/gokul/node_modules/bigchaindb-driver/dist/node/transaction/makeTransferTransaction.js:35:33)     at transferAsset (/home/gokul/Documents/BigchainDB/role.js:244:43)     at createUser (/home/gokul/Documents/BigchainDB/role.js:180:30)     at <anonymous>     at process._tickCallback (internal/process/next_tick.js:118:7) (node:5507) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3) (node:5507) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### ISSUE THREAD

**Issue by GokulSreenivasa** [marmelab/EventDrops#235]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](https://stackoverflow.com/questions/tagged/event-drops).

**What you were expecting:**

**What happened instead:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Environment**

* EventDrops version
* Browser:
* Stack trace (in case of a JS error):

**Comment by jpetitcolas** [comment]
This is not an EventDrops related issue:

> TypeError: unspentOutputs.map is not a function at Object.makeTransferTransaction (/home/gokul/node_modules/bigchaindb-driver/dist/node/transaction/makeTransferTransaction.js:35:33)

Moreover, please keep the title short and concise. It will ease readability. :)
