### ISSUE TITLE
Sample code not working anymore

### ISSUE THREAD

**Issue by Pankesh88** [marmelab/EventDrops#244]
I was trying to get this code up and running.

D3 version: 5.4
event-drops version: 1.2.0

The timeline diagram is showing up, with name property being displayed, but no data point is being potted, there is no error in console.

Regards.

**Comment by GbalsaC** [comment]
Same here, showing code for example, as mine is sitting in angular:

```javascript
import { Component, OnInit, ViewChild, ElementRef, Input } from '@angular/core';

import * as d3 from 'd3';

import eventDrops from 'event-drops';

const chart = eventDrops({ d3 });

const repositoriesData = [
  {
    name: 'admin-on-rest',
    data: [{ date: new Date('2018/06/15 14:21:31') } /* ... */],
  },
  {
    name: 'event-drops',
    data: [{ date: new Date('2018/06/15 13:24:57') } /* ... */],
  },
  {
    name: 'sedy',
    data: [{ date: new Date('2018/06/15 13:25:12') } /* ... */],
  },
];


@Component({
  selector: 'app-event-drops',
  templateUrl: './event-drops.component.html',
  styleUrls: ['./event-drops.component.scss']
})
export class EventDropsComponent implements OnInit {

  data: any;
  @ViewChild('eventDrops') svg: ElementRef;
  @Input('data') set _data(input) {
    this.data = input;
  }
  constructor() { }

  ngOnInit() {
    console.log('SVG: ', this.svg);
    d3
      .select('#eventDrops')
      .data([repositoriesData])
      .call(chart);
  }

}
```

```html
<svg #eventDrops id="eventDrops" width="100%" height="380" class="eventDrops">
</svg>
```

What I'm seeing:
![image](https://user-images.githubusercontent.com/5886517/41187279-a482dace-6b6b-11e8-80ba-49c246faf820.png)

**Comment by ozzi-** [comment]
Same:
`const dataval = [
  {
    "name" :"Email Opened",
    "data" : [
      {
        "date": "2018-05-18T07:51:03.54081282Z",
        "message": "Email Opened"
      },
      {
        "date": "2018-05-18T08:03:20.839679861Z",
        "message": "Email Opened"
      },
      {
        "date": "2018-05-18T09:52:28.505622162Z",
        "message": "Email Opened"
      },
      {
        "date": "2018-05-18T09:52:30.403764868Z",
        "message": "Email Opened"
      },
      {
        "date": "2018-05-18T13:54:29.201352439Z",
        "message": "Email Opened"
      },
      {
        "date": "2018-05-18T15:33:56.828551898Z",
        "message": "Email Opened"
      },
      {
        "date": "2018-05-18T15:34:04.245831818Z",
        "message": "Email Opened"
      },
      {
        "date": "2018-05-22T06:50:54.482882076Z",
        "message": "Email Opened"
      },
      {
        "date": "2018-06-12T09:02:05.130496516Z",
        "message": "Email Opened"
      },
    ],
  }
];
const chart = eventDrops({ d3 });
d3
    .select('#chart')
    .data([dataval])
    .call(chart);
`

Results in
https://i.imgur.com/6YSxt6q.png

**Comment by p0wl** [comment]
any update on this? I can't get the timeline to show anything

**Comment by GbalsaC** [comment]
There is an issue with D3 versioning that supports this repo. 
Newest versions of D3 will not work with this repo anymore @p0wl

**Comment by ozzi-** [comment]
Which versions are working ?

**Comment by scalway** [comment]
this works (version 1.2.0): https://jsfiddle.net/6rqxusw5/290/
this not (version 1.3.0): https://jsfiddle.net/6rqxusw5/9/

**Comment by pradeep-kooky** [comment]
> Same here, showing code for example, as mine is sitting in angular:
> 
> ```js
> import { Component, OnInit, ViewChild, ElementRef, Input } from '@angular/core';
> 
> import * as d3 from 'd3';
> 
> import eventDrops from 'event-drops';
> 
> const chart = eventDrops({ d3 });
> 
> const repositoriesData = [
>   {
>     name: 'admin-on-rest',
>     data: [{ date: new Date('2018/06/15 14:21:31') } /* ... */],
>   },
>   {
>     name: 'event-drops',
>     data: [{ date: new Date('2018/06/15 13:24:57') } /* ... */],
>   },
>   {
>     name: 'sedy',
>     data: [{ date: new Date('2018/06/15 13:25:12') } /* ... */],
>   },
> ];
> 
> 
> @Component({
>   selector: 'app-event-drops',
>   templateUrl: './event-drops.component.html',
>   styleUrls: ['./event-drops.component.scss']
> })
> export class EventDropsComponent implements OnInit {
> 
>   data: any;
>   @ViewChild('eventDrops') svg: ElementRef;
>   @Input('data') set _data(input) {
>     this.data = input;
>   }
>   constructor() { }
> 
>   ngOnInit() {
>     console.log('SVG: ', this.svg);
>     d3
>       .select('#eventDrops')
>       .data([repositoriesData])
>       .call(chart);
>   }
> 
> }
> ```
> 
> ```
> <svg #eventDrops id="eventDrops" width="100%" height="380" class="eventDrops">
> </svg>
> ```
> 
> What I'm seeing:
> ![image](https://user-images.githubusercontent.com/5886517/41187279-a482dace-6b6b-11e8-80ba-49c246faf820.png)

The same thing possible in react-native?
