### ISSUE TITLE
Bug Correction, Colors and radius drops are flickering on the screen.

### ISSUE THREAD

**Issue by christianmerour** [marmelab/EventDrops#257]
# Colors and radius drops are flickering on the screen. #

### I have in my code ###
```
drop : {
                date  :  function(d) { 
                    return moment.unix(d.date_add);
                },
                color :  function(d, index) { 
                    var action = d.action;
                    if (action === 'login') {
                        //console.debug('>>>>>> login', d);
                        return 'green';
                    } else if (action === 'access') {
                        return 'black';
                    } else if (action === 'refresh') {
                        //console.debug('>>>>>> refresh', d);
                        return 'blue';
                    } else if (action === 'logout') {
                        //console.debug('>>>>>> logout', d);
                        console.debug('>>>>>> red logout index', index);
                        return 'red';
                    }
                    console.error('>>>>>> YELLOW ? ', d);
                    return 'yellow';
                },
```
### Then ###
Colors and radius drops are flickering on the screen.

## Bug Origine ##
Bad .merge(drops) usage...

## Bug Correction ##
File : drop.js
### Original ###
```
   drops
        .enter()
        .append('circle')
        .classed('drop', true)
        .attr('r', dropRadius)
        .attr('fill', dropColor)
        .on('click', onClick)
        .on('mouseover', onMouseOver)
        .on('mouseout', onMouseOut)
        .merge(drops)
        .attr('cx', d => xScale(dropDate(d)));
```
### Modified ###
```
   drops
        .enter()
        .append('circle')
        .classed('drop', true)
        .on('click', onClick)
        .on('mouseover', onMouseOver)
        .on('mouseout', onMouseOut)
        .merge(drops)
        .attr('r', dropRadius)
        .attr('fill', dropColor)
        .attr('cx', d => xScale(dropDate(d)));
```

**Comment by christianmerour** [comment]
https://github.com/marmelab/EventDrops/issues/241

**Comment by Daviziu** [comment]
Oh that explains why it wasn't working for me either.

**Comment by eljenso** [comment]
@christianmerour Can you please open a PR with your proposed solution?
The chance of a maintainer to include your fix is higher with a PR. :slightly_smiling_face:

**Comment by shivavelingker** [comment]
I'm still experiencing flickering. The radius for each drop is determined by a function that multiples the drop's value by ten `d => d.value * 10`. With any scroll or zoom, there's flickering. In the case of scrolling, some drops change from very large to very small (or vice-versa) without a change in the data. Was this bug fully fixed or is there a problem with my own code?

**Comment by Busteren** [comment]
@shivavelingker did you get the latest from Master/which version are you using? 1.3.0 which is the latest release does not have the changes. 

Let me know and if you still have the issue after getting the latest, comment and I will see if I can have a look

**Comment by JavierAbrego** [comment]
Hello, We are experiencing the same problem with the latest version from npm.
@ThieryMichel or @jpetitcolas could you please publish a new version into NPM with the changes?

**Comment by Busteren** [comment]
@JavierAbrego I don't have access to NPM or able to do any of the merges as I just contribute, but yes that would be ideal (I think they are looking to add some of the PR to 1.4 as well).

**Comment by JavierAbrego** [comment]
Thanks, let's see if some maintainer can answer It's been more than a year since the last publish. I think that a new one could be handy.
![Screenshot 2019-06-21 at 10 25 44](https://user-images.githubusercontent.com/7070042/59909004-fefda700-940e-11e9-9dc6-e7c146322fc9.png)
