### ISSUE TITLE
Dynamic Event Drop Color Value Switches on Zoom

### ISSUE THREAD

**Issue by Rheisen** [marmelab/EventDrops#267]
**What you were expecting:**

I'm creating an event dropper chart for messaging information, and one thing attached to messages is a sentiment score. The score values are from [-1,1] and I'd like to set the event drop color to scale from red to green depending on the score value.

```
drop: {
          date: (data: any) => data.date,
          color: (data : any) => this.renderDropColor(data),
          ...
}

renderDropColor(data: any) {
    if (typeof data.eventData.dropColor === 'undefined') {
      if (data.eventData.type === 'sentimentScore') {
        const score = data.eventData.sentimentScore;
        const redVal = score <= 0 ? 255 : Math.round(255 - Math.abs(255 * score));
        const greenVal = score >= 0 ? 255 : Math.round(255 - Math.abs(255 * score));
        data.eventData.dropColor = `rgba(${redVal}, ${greenVal}, 0, 1)`;
      } else {
        data.eventData.dropColor = '';
      }
    }
    return data.eventData.dropColor;
}
```

This code works initially and sets the event drop color as expected.

**What happened instead:**

When zooming in or out on the data set, however, the drop color values shift around. My best determination is that when a drop disappears off the edges of the chart the color value of that event drop for some reason moves onto nearby event drops that are still rendered in the display.

**Steps to reproduce:**

In order to reproduce the bug I believe an event dropper chart with dynamically set event drop colors should display the bug. Zooming in and out should create the described behavior where drop colors switch around.

**Related code:**

```
drop: {
          date: (data: any) => data.date,
          color: (data : any) => this.renderDropColor(data),
          ...
}

renderDropColor(data: any) {
    if (typeof data.eventData.dropColor === 'undefined') {
      if (data.eventData.type === 'sentimentScore') {
        const score = data.eventData.sentimentScore;
        const redVal = score <= 0 ? 255 : Math.round(255 - Math.abs(255 * score));
        const greenVal = score >= 0 ? 255 : Math.round(255 - Math.abs(255 * score));
        data.eventData.dropColor = `rgba(${redVal}, ${greenVal}, 0, 1)`;
      } else {
        data.eventData.dropColor = '';
      }
    }
    return data.eventData.dropColor;
}
```

I believe this is the majority of related code, but if anything else would help let me know.

```
insert short code snippets here
```

**Other information:**

**Environment**

* EventDrops version: ^1.3.0
* Browser: Chrome

**Comment by Busteren** [comment]
Reisen, have you tried latest master? 1.3.0 has some known issues

**Comment by Rheisen** [comment]
@Busteren I'll give it an update now, but I started the project I'm working on two days ago so I imagine it is fairly up to date?

**Comment by Busteren** [comment]
The current release is 1.3.0. However, there are some bugfixes not release yet, which I think might cause this error. So download latest master and run the **build** command in makefile

**Comment by Rheisen** [comment]
I tried `npm install --save https://github.com/marmelab/EventDrops`, but got this error: Module not found: Can't resolve 'event-drops'

First time getting a package from GitHub I'm sorry -- is this not what you meant?

**Comment by Busteren** [comment]
Do this:
`git clone https://github.com/marmelab/EventDrops.git`
Go to that folder and ensure you are on master (should be by default)
Then do:
`make build`
Should now be under dist/ folder

**Comment by Rheisen** [comment]
@Busteren Awesome that worked perfectly! Everything looks good now. Is there a better way to automate that process outside of replacing the node_modules/event-drops files with the files from the dist/ folder?

**Comment by Busteren** [comment]
Not sure if I would replace files in node_modules as they would be overwritten when you do install as you mention. Maybe have a js/ folder or something along those lines?

**Comment by Rheisen** [comment]
Good suggestion, that does sound like a better approach. I'll give that a shot!
