### ISSUE TITLE
Issue with scrolling or dragging events with different sizes  and colors.

### ISSUE THREAD

**Issue by badyalgaurav** [marmelab/EventDrops#274]
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](https://stackoverflow.com/questions/tagged/event-drops).

**What you were expecting:**

**Circle are changing there attributes size and color between each other:**

**Steps to reproduce:**

```
 drop: {
      radius: d => {    
        if (parseFloat(d.contribution_score) > 0.8) {
          return 10;
        } else {
          return 5;
        }
      }, //radius of the circle
color: data => {
             if (parseFloat(data.contribution_score) > 0.8) {
          return "black";
        }
```

**Other information:**

**Environment**

* EventDrops version I am using ^1.0 version.
* Browser:
* Stack trace (in case of a JS error):

**Comment by Busteren** [comment]
Have you tried the latest from master (clone and build it)? There's a bugfix regarding colour and drops.
Also what specific version are you using?

**Comment by badyalgaurav** [comment]
I am using from jquery files
<link href="https://unpkg.com/event-drops/dist/style.css" rel="stylesheet" />

<script src="https://unpkg.com/d3"></script>
<script src="https://unpkg.com/event-drops"></script>
So, with these there is issue. I am not extractly know which version is this... but probably it will be latestt. Because this is CDN.

**Comment by Busteren** [comment]
It's the latest version (1.3.0) release. There is a bug with flickering colours:
https://github.com/marmelab/EventDrops/issues/257
is this the issue you are experiencing?
If so it is fixed in the latest of master, but not yet made a new publish on NPM (I just contribute so can not change this).

I would recommend you get the latest from master and use that instead of the CDN, as it contains a few bug fixes! If not, let me know and I can have a look if you link to a minimal example of your problem.

**Comment by badyalgaurav** [comment]
http://eduvis2.unist.ac.kr:2021/dashboard

this is the link where you can find the event drop as history timeline I am using. when you move the timeline then flickering colors.

**Comment by badyalgaurav** [comment]
Okay Thank you, I will build and test it. Then I will give my final comment
on this open channel.

**Comment by badyalgaurav** [comment]
Hey Busteren, I tried to build the project using npm for getting the js file. Although I can run the project by building it but unable to get the js file as I want to add only the js file. It would be appreciated if you provide me the javascript file after build it.

**Comment by badyalgaurav** [comment]
Thank you very much, it is successfully done after changing to the update version js file.
