### ISSUE TITLE
Uncaught TypeError: d3.chart.eventDrops(...).eventClick is not a function

### ISSUE THREAD

**Issue by mydudechris** [marmelab/EventDrops#28]
I'm using this with ZeptoJS and getting the above when I use the eventClick method.

````javascript
    var eventDropsChart = d3.chart.eventDrops().eventClick(function(el) {...});
````

````javascript
      ready: function(callback){
      if (readyRE.test(document.readyState) && document.body) callback($)
      else document.addEventListener('DOMContentLoaded', function(){ callback($) }, false)
      return this
    },...
````

The above is created by Zepto and this is included in the output.

http://cl.ly/image/011i2m332x1u

**Comment by mydudechris** [comment]
Hellur?

**Comment by mydudechris** [comment]
Hello, I've updated my src and am no longer using Zepto. Sadly this error still exists.

**Comment by mydudechris** [comment]
It seems that the version installed by npm vs. the latest source do not match. I manually copied the version available here to my node_modules folder and eventClick works. However, eventHover now fails :(

**Comment by mydudechris** [comment]
Yup, just confirmed by running npm install... again with the eventdrops.js and watched eventclick disappear.

**Comment by dimiii** [comment]
The reasons for this -  addition of `eventClick` was merged on 4 of june (see: https://github.com/marmelab/EventDrops/pull/25). But latest release was shiped on 1 of june (https://github.com/marmelab/EventDrops/releases).

So we have what we have.

**Comment by jpetitcolas** [comment]
Next version of this lib will be published at the end of the week, tagged under the `0.2.0` version. It should be backward compatible, yet as the code has been fully rewritten, some may encounter issues with internal method calls. Hence the version bump.
