### ISSUE TITLE
Data arrays with similar names stack

### ISSUE THREAD

**Issue by mydudechris** [marmelab/EventDrops#29]
http://cl.ly/image/1H3f0o3C3d03

Should this see each name in the data array as a unique row? I duplicated the names in my array using one of your examples and it stacked all those entries. They get their own row and data when the name is unique.

**Comment by jpetitcolas** [comment]
Sorry for the delay... I wasn't able to reproduce the issue.

![image](https://cloud.githubusercontent.com/assets/688373/12776435/349edd4c-ca56-11e5-9d35-f87e87a8b15c.png)

Can you try on latest master version? We did indeed a big refactoring and code cleaning recently.

**Comment by k0emt** [comment]
I think the original poster may be referring to https://github.com/marmelab/EventDrops/blob/master/demo/demo.js and in line 25 if you simply change 10 to 15 without adding additional names[] items you get odd behavior with the label of the last row.

**Comment by jpetitcolas** [comment]
In this case, I got the following behavior:

![image](https://cloud.githubusercontent.com/assets/688373/12809785/201f2e18-cb22-11e5-9174-32d9085fbf6a.png)

Label are then `undefined`. But that's not an issue IMO, as we should not have this case of data in real-world.

**Comment by k0emt** [comment]
Here is a capture of the overwriting behavior I'm seeing.  I do agree, that once you understand why it's happening that it really shouldn't be an issue.

<img width="316" alt="eventdrops_overwrite" src="https://cloud.githubusercontent.com/assets/954691/12999518/c01a04f8-d115-11e5-8ce4-25b673f6d8ea.png">

**Comment by jpetitcolas** [comment]
With which version have you this behavior? Can you try with latest master version?

**Comment by k0emt** [comment]
I confirm works as expected with pull from master. 

Best regards,

Bryan
