### ISSUE TITLE
zoomRect appears black

### ISSUE THREAD

**Issue by Kallirroi** [marmelab/EventDrops#31]
Hello,
I am creating a medical events timeline, and have trouble with the zoomRect SVG appearing black - see image.
Adding .style("opacity", 0) to its declaration seems to do the trick.
Any ideas why it appears black in the first place?
Thanks!

![zoomrect](https://cloud.githubusercontent.com/assets/10440556/8316733/eda65d7e-19c6-11e5-9be3-880afca8577b.png)

**Comment by ThieryMichel** [comment]
Did you include the css?

**Comment by Kallirroi** [comment]
Here it is:
.zoom {
    fill: transparent;
    cursor: pointer;
}

.graph-body .line circle {
    opacity: 0.5;
}

.axis path,
.axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}
.x.axis path {
display: none;
}

h2{
    font-size: 18px;
}
div{
    position: relative;
}
legend {
    font-size: 15;
}

**Comment by jpetitcolas** [comment]
Sorry for this huge delay... You need to add:

```
.zoom-area {
    fill: transparent;
    cursor: pointer;
}
```
