### ISSUE TITLE
Disabling zoom

### ISSUE THREAD

**Issue by maherbeg** [marmelab/EventDrops#38]
How do you disable zooming with the mouse wheel for the chart? I'm having trying the various mechanisms to unbind the zoom behavior on the chart itself. We'd ideally like to control zooming behavior with a separate control to prevent capture of the mouse.

**Comment by maherbeg** [comment]
Ah, figured it out. May be worth enabling as a config option.

```javascript
  d3.select($('rect.zoom')[0]).call(zoom);
```

**Comment by slifty** [comment]
Thank you @maherbeg I had the same situation!

**Comment by maherbeg** [comment]
@slifty I actually ended up not using that. I cheated and proxied `addEventListener` to enable toggling of the zooming function.

```javascript
var proxiedAdd = Element.prototype.addEventListener;
  var enableZoom$ = $('#zoom-element');
  Element.prototype.addEventListener = function(type, listener, useCapture) {

    var listenerToAdd = listener;
    if (type === 'wheel') {
      listenerToAdd = function() {
        if (enableZoom$.is(':checked')) {
          listener.apply(this, arguments);
        }
      };
    }
    proxiedAdd.call(this, type, listenerToAdd, useCapture);
  };
```

**Comment by jpetitcolas** [comment]
Indeed, it should be configurable. We are currently working on the next version. Let's add it the new configuration file. :)
