### ISSUE TITLE
changing the event icon

### ISSUE THREAD

**Issue by mkssion** [marmelab/EventDrops#45]
is it possible to change the circle to a rectangular or a line?

and if this is possible, is it possible to change the rectangular's size when zooming?
What I want is that the rect. would get broader the further you zoom in, so that events which follow each other look like a big single rect.?

Hope it is somehow clear what I mean...

**Comment by fzaninotto** [comment]
See the new demo / GIF in the project homepage : the shape of individual events is no longer an issue, since we're metaballing te events to show uneven distributions.

**Comment by jpetitcolas** [comment]
The incoming demo link is: http://marmelab.github.io/EventDrops

It is not yet finalized, some style adjustments are still required. But metaballs are now visible.
