### ISSUE TITLE
Style.css isn't a valid css file

### ISSUE THREAD

**Issue by maxyeg** [marmelab/EventDrops#47]
https://github.com/marmelab/EventDrops/blob/master/css/style.css
has errors.
Please make it a valid css file.

Major error is https://github.com/marmelab/EventDrops/blob/master/css/style.css#L11.
The `path` class here is treated like a name of a property in plain css. 
If your `style.css` would be `style.scss` it could be so.

The problem which I encounter is that I have a `*.scss` file in which I'm going to import your `style.css`
And sass processing fails with error:

// Unhandled 'error' event
Error: property missing ':' near line 11:9

it's because of your `style.css` is treated as plain css. If I rename your file to `style.scss`, it's imported correctly, because scss can handle such syntax.

Also CSS editor shows minor warning on line 9, it contains unneeded comma.

**Comment by ThieryMichel** [comment]
Should get fixed by #48
