### ISSUE TITLE
Add a way to put the label inside the Chart instead of outside

### ISSUE THREAD

**Issue by grillorafael** [marmelab/EventDrops#51]
I can do it with CSS only but then the label is below the chart.

![image](https://cloud.githubusercontent.com/assets/1812267/11659762/c32425f2-9dc1-11e5-85b4-72ba195b3fe3.png)

**Comment by jpetitcolas** [comment]
How did you do it with CSS?

I don't think that's a use case we need to support, as it is quite specific. However, for narrow spaces, we may perhaps add an option to disable labels? Then, in this case, you would be able to add them back using pure CSS, and playing with element z-indexes?

**Comment by grillorafael** [comment]
Hey @jpetitcolas I don't remember exactly but I think I removed the margin and maybe changed the text-anchor.

But since the time I opened this issue I really improved my knowledge on D3 so I think I'll try to open a PR for this.

About the css z-index, it didn't work because the z-index was defined by the order of elements on SVG. 

About the use case, I think it is nice to support because it fits better when adding the chart to some sort of box.

**Comment by jpetitcolas** [comment]
A PR has been created to put labels over the drops (#234). Then, using some negative label padding, you should be able to put labels inside your chart (at least on version `1.1.x`):

```js
const chart = eventDrops({
    label: {
        padding: -200,
    },
};
```
