### ISSUE TITLE
Large black box across visualization

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/EventDrops#55]
Issue received by email:

> When trying out the demo with the current CSS sheet (https://github.com/marmelab/EventDrops/blob/master/css/style.css) I get a large black box across the visualization.  If I pull down the CSS (http://marmelab.com/EventDrops/style.css) that is used for http://marmelab.com/EventDrops/ it renders correctly.

**Comment by k0emt** [comment]
When I pull down the code (git clone) there is no style.css in the https://github.com/marmelab/EventDrops/tree/master/demo directory.
So, I then copy the style.css from https://github.com/marmelab/EventDrops/blob/master/css/style.css
Viewing on Linux w/Chrome, FF or Windows w/Chrome and I get a large black box on top of the visualization.

So, I went out to the website http://marmelab.com/EventDrops/ viewed the source and pulled down the style.css from there: http://marmelab.com/EventDrops/style.css  They are significantly different.  With this style sheet the visualization appears correctly.

**Comment by jpetitcolas** [comment]
Should be fixed by #56. The `style.css` file would then be compiled by Webpack.

**Comment by jpetitcolas** [comment]
#56 has been merged. Feel free to re-open if you still encounter the issue.
