### ISSUE TITLE
AMD Compatability

### ISSUE THREAD

**Issue by gavinr** [marmelab/EventDrops#59]
Would it be possible to wrap the provided built files using the [UMD](https://github.com/umdjs/umd) specification? That way we could use it in the AMD world too.

Thanks for the great plugin!

**Comment by gavinr** [comment]
I believe this should be possible by adding the `transform-es2015-modules-umd` plugin in `.babelrc` (haven't tested though).

https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-umd

**Comment by jpetitcolas** [comment]
I just changed configuration of Webpack to export lib as an UMD module. Should be available soon (probably today on master).
