### ISSUE TITLE
Getting event name on eventHover/eventClick

### ISSUE THREAD

**Issue by GeorgeL9** [marmelab/EventDrops#63]
I have events, that I want to display a tooltip for with the repo name of the event.

```
var data = [
         {
             name: "Stars",
             dates: [new Date('2014/09/15 13:24:54'), new Date('2014/09/15 13:25:03')],
            repos: ['test/test','debug/debug']
         }, {
             name: "Pushs",
            dates: [new Date('2014/08/15 11:24:54'), new Date('2014/09/15 13:25:03')],
            repos: ['test/test','debug/debug']
         }];
```

Currently `d` returns only the datetime.

**Comment by GeorgeL9** [comment]
So I figured out how to get the index `.eventHover(function (d, i) {...}` but am unable to get the section that it happens in.

**Comment by jpetitcolas** [comment]
Indeed, we need to pass more details via the `d` variable. This is on our roadmap for the 0.3 version. I don't think it is possible for now, unless that you are sure that every date is unique, which is unlikely the case.

**Comment by GeorgeL9** [comment]
In my case, there is a very high chance for overlap in timing.

**Comment by irvins** [comment]
Hi @jpetitcolas ,  There is no way to correlate the event to the date at the moment?

**Comment by felixdasgupta** [comment]
This would be a very nice addition. I am also have difficulty with this issue.

Currently unable to retrieve information about the section in which the circle belongs to i.e. "name" in this example. 

Retrieving the date is not an issue. However there are no unique dates that would help identify which section the circle belongs to... This makes it rather difficult to build informative tooltips or features around the eventDrops charts...

**Comment by jpetitcolas** [comment]
PR #76 should fix the issue.

**Comment by jpetitcolas** [comment]
#76 has just been merged. Should be fixed on master.
