### ISSUE TITLE
How can I draw dynamic line on the control

### ISSUE THREAD

**Issue by xiangjian** [marmelab/EventDrops#64]
I want to use this event to make a video playback control? I would like to add this control function
When the progress of the video player during playback may occur on the controls to play.

How can I draw dynamic line on the control
![image](https://cloud.githubusercontent.com/assets/460697/13273994/9cb4e9de-dae2-11e5-8464-bb813f8c0114.png)

**Comment by jpetitcolas** [comment]
It is not supported by EventDrops, and won't be, as it is a very specific feature. However, you can do it by hand, adding a vertical line over the chart, and moving it using some D3.js. Something like:

``` js
        const drawCurrentTimeLine = (container, height, date) => {
            const timeline = d3.select(container)
                .selectAll('.timeline')
                .data([{ date }]);

            timeline.enter()
                .append('line')
                .attr({
                    class: 'timeline',
                    y1: 0,
                    y2: height,
                    x1: d => d.date,
                    x2: d => d.date,
                });

            timeline.attr({
                x1: d => d.date,
                x2: d => d.date,
            });
        };
```

This code has not been tested, and would probably need more work to achieve your purpose. But that's a good start in my opinion.
