### ISSUE TITLE
The points overlap the labels in Firefox in the demo

### ISSUE THREAD

**Issue by stof** [marmelab/EventDrops#65]
When zooming on the demo (through the mouse scroll), the points overlap over the labels instead of disappearing. This is not the same behavior than the one shown in the gif in the readme.
I'm using Firefox 44.0.2 on Ubuntu 14.04

![event_drops](https://cloud.githubusercontent.com/assets/439401/13286444/d22889f8-db01-11e5-8865-e2c1e67ef80b.png)

**Comment by stof** [comment]
I tried the demo with Chromium and Opera and they are not affected by this bug.

**Comment by jpetitcolas** [comment]
Thanks for reporting the issue. Indeed, we just needed to check everything was fine on major browsers. We'll need to fix that for 0.2 release. :)
