### ISSUE TITLE
eventClick not a function?

### ISSUE THREAD

**Issue by yxjames** [marmelab/EventDrops#67]
I saw a closed issue about this, said the eventClick function disappeared. I'm looking at the 0.1.2 version and eventClick is still not here?

**Comment by jpetitcolas** [comment]
Indeed, no new version has been published. The `0.2`, fixing the issue, is incoming (beginning of next week, time for us to write a blog post describing the changes). 

You can use current master build meanwhile.

**Comment by jpetitcolas** [comment]
`0.2.0` has been published. You can get more info on what is new on [our blog post](http://marmelab.com/blog/2016/03/09/eventdrops-0.2-is-out.html).
