### ISSUE TITLE
Mouse wheel zoom coordinate is wrong.

### ISSUE THREAD

**Issue by MariasStory** [marmelab/EventDrops#70]
Zooming with the mouse wheel has a wrong zoom center.

The center is shifted to right, also in the online example: http://marmelab.com/EventDrops/

Greetings,
Tolik

**Comment by fzaninotto** [comment]
Yep, I noticed it, too. This is a regression. Zooming used to be centered on the mouse pointer.

**Comment by MariasStory** [comment]
Seems to be related to the <g class="axes" transform="translate(210, 55)">. The offset is exactly 210px.
The only place in your repo where I see something related to wheel and zoom is "function eventDrops(config)" in bundle.map.json
I don't really understand why this json with function is there?
Please fix the bug.

**Comment by MariasStory** [comment]
Something is cleaned from previous post 
`<g class="axes" transform="translate(210, 55)">`

**Comment by jpetitcolas** [comment]
Not sure what is the `bundle.map.json`. Probably a remainder of oldest versions. We will try to remove it. 

How did you compute the exact offset?

**Comment by MariasStory** [comment]
To have a fast and dirty fix:
Replase:
`<g class="axes" transform="translate(210, 55)">`
to
'<g class="axes" transform="translate(0, 55)">'
and add
'transform="translate(-210, 0)"'
to
'class="drops-container"'
Now your chart overlaps with your left axes :-(.

**Comment by MariasStory** [comment]
again not all text is shown:
first replase to
`<g class="axes" transform="translate(0, 55)">`

**Comment by jpetitcolas** [comment]
Thanks for these useful extra informations. It is probably related to the fact we apply the zoom on the whole chart, but not only on the drop lines. It doesn't make sense: when zooming on a label, where should we put zoom center? 

I'm looking at it.

**Comment by MariasStory** [comment]
Strange that you did not fix the problem jet.

In https://github.com/marmelab/EventDrops/blob/master/lib/drawer/index.js

Line 28 I see:

>         .attr('transform', 'translate(210, 55)');

Maybe this gives and idea?

Try to play with the arguments and see what happens!

**Comment by MariasStory** [comment]
Ping.

This bug spoils all experience.

Please fix it.
