### ISSUE TITLE
EventDrops local server

### ISSUE THREAD

**Issue by carlobailey** [marmelab/EventDrops#71]
Forgive me for such an amateur question - I am new to javascript/html.

I am trying to use the EventDrops chart on a local webpage - but keep getting this 'Uncaught SyntaxError: Unexpected token import' which is pointing to a syntax error in the 'eventDrops.js' file.

Can anyone help? Thanks!!

**Comment by jpetitcolas** [comment]
It seems you are using the source file, written in ES6, for EventDrops developers purposes. Have you tried using the files in `dist/` folders? Both JS and CSS? :)

**Comment by carlobailey** [comment]
OK, got it. 
Works perfectly, Thank you!
