### ISSUE TITLE
Uncaught TypeError: t.map is not a function eventDrops.js:15 

### ISSUE THREAD

**Issue by carlobailey** [marmelab/EventDrops#72]
Hello Again,

I am having issues when pulling in my data from a local server. I am trying to figure out if the issues is from the way I am structuring the array or whether it is an issue within the eventDrop.js file (which is where the error is showing). As I am new to D3 I am guessing the former. I am bringing the data from python and thus have to convert from UNIX to javascript Date object. 

``` js
myData = {
    "sensor1": [
        1458068401000,
        1458068401000,
        1458068403000,
        1458068404000,
        1458068405000,
        1458068406000,
        1458068411000,
        1458068413000,
        1458068415000,
        1458068416000
    ]
}
```

my Code

``` js
// function that converts UNIX to Date object
function mapDates(value){
    output = new Date(value);
    return output;
}
var testdata = [];
var newdates = [];
d3.json("./datatest.json", function(data)
{   
    
    var count = Object.keys(data)
    for (i in count)
    {
        testdata.push(data[count[i]].map(mapDates))
        newdates.push({count:testdata})
        console.log(newdates)
        
    }
    var eventDropsChart = d3.chart.eventDrops()
    var canvas = d3.select("body").selectAll("p")
    d3.select('body')
    .datum(newdates)
    .call(eventDropsChart);
    
    
})`   
```

the error: Uncaught TypeError: t.map is not a function eventDrops.js:15 

Please help! Thanks

**Comment by carlobailey** [comment]
Update: I simplified the script and hard coded the data and still getting the same error. Is it because I am converting UNIX to a Date object? This is line 15 of the eventDrop.js file that is throwing the error: `.domain(data.map((d) => d.name))` 

Here's my code
`var harddata = {"sensor1": [new Date(1458068401000), new Date(1458068401000), new Date(1458068403000), new Date(1458068404000), new Date(1458068405000), new Date(1458068406000), new Date(1458068411000), new Date(1458068413000), new Date(1458068415000), new Date(1458068416000)]};

        d3.select("body").selectAll("p")

        var eventDropsChart = d3.chart.eventDrops()
        .eventColor('blue')
        .width(1800);

        d3.select('body')
          .datum(harddata)
          .call(eventDropsChart);`

**Comment by jpetitcolas** [comment]
You need to pass an array of data, each of them containing a `name` and an array of `dates`:

``` js
var hardData = [{
    name: 'sensor1',
    dates: [
        new Date(1458068401000),
        new Date(1458068401000),
        new Date(1458068403000),
        new Date(1458068404000),
        new Date(1458068405000),
        new Date(1458068406000),
        new Date(1458068411000),
        new Date(1458068413000),
        new Date(1458068415000),
        new Date(1458068416000),
    ],
}];

var eventDropsChart = d3.chart.eventDrops()
    .eventColor('blue')
    .width(1800);

d3.select('body')
    .datum(hardData)
    .call(eventDropsChart);
```

You also have a useless call with `selectAll('p')`. :)

Note: for better code formatting, use ` ` ` js (without spaces between back quotes).

**Comment by jpetitcolas** [comment]
You even don't need call to the `new Date()` constructor: it also works with just some timestamps.

**Comment by carlobailey** [comment]
Thank you for the prompt response and being patient with my amateur request.

Works like a charm

**Comment by StudioAleph** [comment]
what I do wrong?

this cod was running correctly but suddenly shows error

`
resnderStudent(){
    return this.state.ProductList.map(Products=>
      <ListItem key={Products.Id}>
        <Left>
           <Body style={{ flex:1, flexDirection: 'row' }}>
              <Button icon transparent  style={{width:27,padding:0}} onPress={this.LessProduct.bind(this,Products.Id)}>
                 <Left>
                   <Icon type="FontAwesome" name="minus-circle" style={{fontSize:30,color:'blue'}}/>
                 </Left>
              </Button>
              <Text style={{ minWidth:20, textAlign:'center',alignSelf: 'center'}}>
                 {this.props.ShowCount[Products.Id]}
              </Text>
              <Button icon transparent style={{width:27,padding:0}} onPress={this.UserOrderBasket.bind(this,Products.Id)}>
                 <Left>
                    <Icon type="FontAwesome" name='plus-circle' style={{fontSize:30,color:'blue'}}/>
                 </Left>
              </Button>
           </Body>
        </Left>
        <Body>
          <Text>{Products.Name}</Text>
          <Text note>توضیحات کوتاه در باره محصول ... </Text>
        </Body>
        <Thumbnail square size={50} source={{ uri: Products.Photo }} />
      </ListItem>
    );
  }


`

it say's TypeError: this.state.ProductList.map is not a function but it was work 
how can I solve this problem?
