### ISSUE TITLE
No Method to Configure Y-Axis... Words are Cut-Off 

### ISSUE THREAD

**Issue by felixdasgupta** [marmelab/EventDrops#78]
I am unable to configure the margins for the Y-axis Labels on the Left. 

Essentially I have some long worded labels and they are getting cut off when the chart is drawn for Each Row. There is only a method to set the margins for the charts, that is currently not accounting for the margins of the x or y axes. 

Please help. Thanks.

![pv9](https://cloud.githubusercontent.com/assets/9090078/15408216/fd9bc640-1ddc-11e6-89b2-6496b7bcd1dd.png)

**Comment by jpetitcolas** [comment]
PR #73 should probably fix your issue, allowing you to set a custom label width. It should be merged very soon and be available in the 0.3.

**Comment by felixdasgupta** [comment]
Thanks! Looking forward to it

**Comment by jpetitcolas** [comment]
It should be fixed on latest master version now (PR #73 has been merged).

I let you check and close the issue if everything is fine?

**Comment by felixdasgupta** [comment]
Awesome! Let me check tomorrow...

On Thu, Jul 7, 2016 at 3:16 AM, Jonathan Petitcolas <
notifications@github.com> wrote:

> It should be fixed on latest master version now (PR #73
> <https://github.com/marmelab/EventDrops/pull/73> has been merged).
>
> I let you check and close the issue if everything is fine?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/marmelab/EventDrops/issues/78#issuecomment-231001560>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIq0HvQO23qfH7R1e8H1f4vtEPfl0BuFks5qTKfegaJpZM4IioLk>
> .
>



-- 
Felix Dasgupta
C#: (201)-755-7563
Developer @Hindsait <https://twitter.com/Hindsait>
DJ Felix @adfelix2 <http://soundcloud.com/adfelix2>

TW: @FelixDasgupta <https://twitter.com/FelixDasgupta>
LN: @FelixDasgupta <https://www.linkedin.com/in/felixdasgupta>

**Comment by jpetitcolas** [comment]
Did you check with the new version? Is it OK for you?

**Comment by jpetitcolas** [comment]
Closing as no feedbacks.
