### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.length')

### ISSUE THREAD

**Issue by diflores** [marmelab/EventDrops#83]
Hello,
I've been working with d3 for a while, but I came across with EventDrops just yesterday and loved how it looks like. I put the demo's code into my own script and I keep getting this error:

`TypeError: undefined is not an object (evaluating 'e.length')`

When I delete this line:

`eventDropsChart(element);`

The error disappears, but the chart is not showed, not even the horizontal lines that are drawn when I keep that line in the code.

I've been trying to fix this, but I can't find my error.

I'd appreciate any help,

Thank you in advance!

**Comment by jpetitcolas** [comment]
The line you mention (`eventDropsChart`) is used to draw the chart. So, this is normal that the chart doesn't draw when you remove it. :)

It would be difficult to help you without more information. Can you provide us your code? That's perhaps an issue with your data format. 

Moreover, which version do you use? Master version? Or the `0.2` one?

**Comment by diflores** [comment]
Hello again,
I'm using Master version, here's my code:

```javascript
        var data = [];
        var names = ["Lorem", "Ipsum", "Dolor", "Sit", "Amet", "Consectetur", "Adipisicing", "elit", "Eiusmod tempor", "Incididunt"];
        var endTime = Date.now();
        var month = 30 * 24 * 60 * 60 * 1000;
        var startTime = endTime - 6 * month;

        function createEvent (name, maxNbEvents) {
            maxNbEvents = maxNbEvents | 200;
            var event = {
                name: name,
                data: []
            };
            // add up to 200 events
            var max =  Math.floor(Math.random() * maxNbEvents);
            for (var j = 0; j < max; j++) {
                var time = (Math.random() * (endTime - startTime)) + startTime;
                event.data.push(new Date(time));
            }

            return event;
        }
        for (var i = 0; i < 10; i++) {
            data.push(createEvent(names[i]));
        }

        var color = d3.scale.category20();

// create chart function
        var eventDropsChart = d3.chart.eventDrops()
            .eventLineColor(function (datum, index) {
                return color(index);
            })
            .start(new Date(startTime))
            .end(new Date(endTime));

// bind data with DOM
        var element = d3.select('#eventdrops-demo').datum(data);

// draw the chart
        eventDropsChart(element);

```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard alcaldes</title>
    <link rel="stylesheet" href="./static/semantic.css">
    <link rel="stylesheet" href="./static/eventDrops.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src="./static/d3.min.js" charset="utf-8"></script>
    <script src="./static/eventDrops.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.12/crossfilter.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dc/1.7.5/dc.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dc/1.7.5/dc.min.css">
    <script src="./static/d3.layout.cloud.js"></script>
    <script src="./static/semantic.js"></script>
    <script src="./static/stopwords_es.js"></script>
    <script src="./static/tabs.js"></script>
    <script src="./static/bio.js"></script>
    <script src="./static/charts.js"></script>
</head>
<body>
    <div class="ui one column grid">
        <div class="column">
            <div class="header">
                <h3>Sentimiento</h3>
            </div>
            <div id="eventdrops-demo">
            </div>
        </div>
    </div>
</body>
</html>
```

As you can see, I'm just using the code from the demo.

Thank you for your quick answer!

**Comment by jpetitcolas** [comment]
Executing your code in a JSFiddle seems to work: https://jsfiddle.net/xcjc4Lpz/1/

Which version of D3.js are you using? Can you remove all other dependencies than EventDrops and add them progressively, to check where the error comes from?

**Comment by jpetitcolas** [comment]
Closing as no more feedback.

**Comment by RupaRavulakollu** [comment]
Hello ,
I have been getting error repeatedly when i use the carousel in my code 
when i remove the carousel it works fine .
Can someone find it out?


<Carousel
             ref={(carousel) => { this._carousel = carousel; }}
             sliderWidth={Dimensions.get('window').width}
             itemWidth={Dimensions.get('window').width}
             onSnapToItem={(index) => this.setState({ activeSlide: index }) }
             enableSnap={true}
          >
              {this.renderImages()}
          </Carousel>


This is my code .
![screenshot_20181020-191130](https://user-images.githubusercontent.com/32895412/47256349-4dcbf900-d49c-11e8-953f-9762da4c0fb1.jpg)
