### ISSUE TITLE
Error while installing event-drops using npm

### ISSUE THREAD

**Issue by vignesh14thnov** [marmelab/EventDrops#84]
I wanted to have a  non-minified version of eventDrops.js file for my project. I tried to install event-drops using npm. I installed python and VS2015 as I got errors. after that, the installation did not throw previous errors. But, I'm getting a new error like this: 
> 
> contextify@0.1.15 install D:\temp_eventDropsInstall\node_modules\contextify
> node-gyp rebuild
> D:\temp_eventDropsInstall\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Users\...\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   contextify.cc
>   win_delay_load_hook.c
> C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [D:\temp_eventDropsInstall\node_modules\contextify\build\contextify.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'

Can you please help getting the non minified version of eventDrops.js file?

**Comment by jpetitcolas** [comment]
Can you post the whole output? I can't find any fatal error in your quote. :)

**Comment by vignesh14thnov** [comment]
I'm sorry. Here is the whole output:

> D:\temp_eventDropsInstall>npm install event-drops
> contextify@0.1.15 install D:\temp_eventDropsInstall\node_modules\contextify
> node-gyp rebuild
> D:\temp_eventDropsInstall\node_modules\contextify>if not defined npm_config_node
> _gyp (node "C:\Users\...\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-b
> in\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuil
> d )
> Building the projects in this solution one at a time. To enable parallel build,
> please add the "/m" switch.
>   contextify.cc
>   win_delay_load_hook.c
> C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src
> \win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; d
> ifferent type modifiers [D:\temp_eventDropsInstall\node_modules\contextify\buil
> d\contextify.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
>   ): note: see declaration of '__pfnDliNotifyHook2'
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
> ed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\...\AppData\Roaming\npm\
> node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
> s.js:200:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppD
> ata\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js"
> "rebuild"
> gyp ERR! cwd D:\temp_eventDropsInstall\node_modules\contextify
> gyp ERR! node -v v4.4.5
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> npm WARN enoent ENOENT: no such file or directory, open 'D:\temp_eventDropsInsta
> ll\package.json'
> npm WARN temp_eventDropsInstall No description
> npm WARN temp_eventDropsInstall No repository field.
> npm WARN temp_eventDropsInstall No README data
> npm WARN temp_eventDropsInstall No license field.
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData
> \\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "event-drops"
> npm ERR! node v4.4.5
> npm ERR! npm  v3.8.6
> npm ERR! code ELIFECYCLE
> npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the contextify package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs contextify
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls contextify
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\temp_eventDropsInstall\npm-debug.log

**Comment by jpetitcolas** [comment]
It looks more like a Windows `node-gyp` installation issue than an EventDrops one. Perhaps can you give a try to some solutions given in this [big thread](https://github.com/nodejs/node-gyp/issues/629)?

Closing the issue as we can't fix this issue from our repository. :)

**Comment by nikkiczx** [comment]
Is this issue only limited to Windows? Because I'm getting the same error on MacOS.

**Comment by deevus** [comment]
Getting the same issue on Windows. Does someone know which project is listing `contextify` as a dependency. [Their github README](https://github.com/brianmcd/contextify#you-dont-need-this-module-on-node--012) states that it is not required if you're running node >= 0.12, which I would hope is just about everyone.

**Comment by vmnair** [comment]
Any news on resolution of this issue?
I get the same error when trying npm install on MacOS
