### ISSUE TITLE
No configuration to resolve 'date' from complex datasets

### ISSUE THREAD

**Issue by twisty-n** [marmelab/EventDrops#91]
The `0.2.0` release appears to have removed documented support for a custom function to resolve the date from a more complex data set. 

For example, after installing `EventDrops` from npm, I tried to make an example using the code from the `README` with data of the form
 ```
var data = [
  { name: "http requests", data: [{date: new Date('2014/09/15 13:24:54'), foo: 'bar1'}, {date: new Date('2014/09/15 13:25:03'), foo: 'bar2'}, {date: new Date('2014/09/15 13:25:05'), foo: 'bar1'}, ...] },
  { name: "SQL queries", data: [{date: new Date('2014/09/15 13:24:57'), foo: 'bar4'}, {date: new Date('2014/09/15 13:25:04'), foo: 'bar6'}, {date: new Date('2014/09/15 13:25:04'), foo: 'bar2'}, ...] }
];
```

The docs say that I should be able to configure the chart using `.date(d => d.date)`. However, `date` was at some point removed as a configurable parameter from default `config.js` which means that this function doesn't work and errors out when it is used. 

I was wondering if the documentation on GitHub should be synchronized with the `0.2.0` release, and if there was a new way to use this sort of functionality

**Comment by twisty-n** [comment]
After researching the issue further, it appears the functionality was added in https://github.com/marmelab/EventDrops/commit/9a78b424245215a77d45cd1130571e9752f43a62#diff-f7bf2b665273dfa66ffa4ad7c0a52bb9 which occurs after the `0.2.0` release. 

It might be worth updating the README to indicate `0.2.0` doesn't support the advanced examples

**Comment by deevus** [comment]
Perhaps there could be a pre-release published to npm with the new functionality?
