### ISSUE TITLE
Remove built files from repository

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/EventDrops#93]
As discussed in https://github.com/marmelab/EventDrops/pull/92 by @deevus, we should think about a solution to not pollute diffs and repository with built files. Probably by moving the built files on a dedicated branch and retrieve this release branch for npm releases?

**Comment by deevus** [comment]
Like I mentioned in #92, you could use Travis-CI to publish your releases. 

Since you're already using it, that's what I would do, if it were my choice :+1:
